DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_MATRICULA INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES
(DEFAULT, 9090, 'CRYSTAL', 'RUSH'),
(DEFAULT, 4576, 'CAMILO', 'SAEZ'),
(DEFAULT, 6759, 'CARMEN', 'SANTELICES'),
(DEFAULT, 2343, 'ESTEBAN', 'LONDON'),
(DEFAULT, 6969, 'MIA', 'KHALIFA');